# Generated by Django 3.2.16 on 2022-11-09 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
